### ISSUE TITLE
[0.3.4] "make test" fails with GCC 11 (but not with GCC 9)

### ISSUE THREAD

**Issue by hartwork** [gkdr/axc#26]
Hi @gkdr ,

as I [learned today](https://bugs.gentoo.org/803353#c9) GCC 11 puts the `*.g*` coverage files into the `test/` folder and hence the two `mv *.g* $(TDIR)` calls in the `Makefile` fail, as there is nothing to move. A fix supporting both GCC 9 and 11 could be prefixing them with `-` (dash or "minus") so that make ignores a non-zero return code. What do you think?

Best, Sebastian

**Comment by gkdr** [comment]
hi @hartwork, thanks for the report! sounds like a simple solution that does the trick.

**Comment by hartwork** [comment]
Should I make a pull request or would you rather do that yourself?

**Comment by gkdr** [comment]
actually, merging #27 fixed this issue as well because `find` does not seem to return an error in case the files don't exist, which was also an issue when trying to run the build in parallel. just ignoring the exit code would have been the easiest solution from the start, i guess :grimacing: 

i'm going to close this issue then. feel free to reopen it if you feel i missed something. and sorry it took me so long to respond for such a simple isse.

**Comment by hartwork** [comment]
@gkdr I see, thanks for merging #27. If there is a chance for a release 0.3.5 some time, it will allow me to keep the downstream patch count at ideal zero.If 0.3.5 is not in reach, I can do a cherry-pick for a temporary fix downstream in the mean time.

**Comment by gkdr** [comment]
done, it was about time anyway, thanks for the reminder :D see 78b03d0682761588139cf2cd0174aa303764c298.

**Comment by hartwork** [comment]
@gkdr thanks for the release, [bumped in Gentoo](https://github.com/gentoo/gentoo/commit/33fa09b0dc127aba68a045f84032ed2fd1811cd2) just now.
