### ISSUE TITLE
message_client.c does not compile

### ISSUE THREAD

**Issue by annerajb** [gkdr/axc#5]
It seems message_client.c is referencing old functions that are still on the .h files

axc_handshake_accept
axc_handshake_acknowledge

Are this suppose to be implemented are they needed?

**Comment by gkdr** [comment]
libsignal contained code for synchronous session establishment that was later removed.
I assume this is because you can use the existing asynchronous functions in a synchronous setting by simply sending a request for the data which usually gets uploaded to a server.

When I updated this library, I didn't update the demo code (because it seems this lib isn't too popular anyway, so I thought it's not a hurry. I wrote this on the readme:
>Unfortunately it is currently broken as the synchronous code was removed.

In any case: No, they are not necessary, and compiling this demo is not necessary for the lib to work. But please leave this issue open as a reminder for me to fix it! Until then, I hope the documentation I wrote in the .h files is enough.

**Comment by hartwork** [comment]
@gkdr can this be closed as fixed? Seems to be fixed by commit 1c60f4990e20febc41201ae1b3a9aca5b5de65ac.

**Comment by gkdr** [comment]
4 years... better late than never :grimacing:
